server:
    port: 80

spring:
    profiles:
        active: dev
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://10.26.166.116:3306/love_poprice?useUnicode=yes&characterEncoding=utf-8
        databaseName:
        serverName:
        username: root
        password: qwe123
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        maximumPoolSize: 10
        minimumIdle: 5

#http://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        openInView: true
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update #none, validate, update, create-drop
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false
        mode: HTML


metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: qr-api

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M



